name: finmanage_mobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.1
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+3
  sqflite_common_ffi_web: ^0.4.5+3
  path_provider: ^2.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  font_awesome_flutter: ^10.4.0
  cloud_firestore: ^5.5.1
  firebase_database: ^11.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inder
      fonts:
        - asset: assets/fonts/Inder-Regular.ttf

